In [1]:
import argparse

In [22]:
indices

array([array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2, 3]),
       array([2, 3]), array([4])], dtype=object)

In [12]:
from src.adversarial_attacks_on_feature_dependent_graphs.data import *

In [3]:
sys.path.append('/nfs/homedirs/bindera/Adversarial Attacks on Feature-Dependent GraphsAdversarial Attacks on Feature-Dependent Graphs/src/adversarial_attacks_on_feature_dependent_graphs')

In [13]:
data_folder = '../../../shared/modelnet/modelnet40_normal_resampled'
data_train, data_val, data_test = get_dataset(name = 'modelnet40', data_folder = data_folder)

The size of train data is 9843
Load processed data from ../../../shared/modelnet/modelnet40_normal_resampled/modelnet40_train_1024pts_fps.dat...
The size of test data is 2468
Load processed data from ../../../shared/modelnet/modelnet40_normal_resampled/modelnet40_test_1024pts_fps.dat...


In [2]:
# sys.path.append('../../../reference_implementations/Pointnet_Pointnet2_pytorch/data_utils')
sys.path.append('/nfs/homedirs/bindera/reference_implementations/dgcnn/pytorch')

In [6]:
! mkdir /nfs/students/bindera/logs/DGCNN

In [3]:
from util import cal_loss

/nfs/homedirs/bindera/miniconda3/envs/test_torch/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
! ls /nfs/students/bindera/logs

DGCNN


In [23]:
from model import DGCNN

In [21]:
data_train[42][0].shape

(1024, 3)

In [1]:
def test(x=1,d=2):
    print(locals())

test()

{'x': 1, 'd': 2}


In [7]:
! ls ../../../shared/modelnet/modelnet40_normal_resampled

airplane      glass_box				piano
bathtub       guitar				plant
bed	      keyboard				radio
bench	      lamp				range_hood
bookshelf     laptop				sink
bottle	      mantel				sofa
bowl	      modelnet10_shape_names.txt	stairs
car	      modelnet10_test.txt		stool
chair	      modelnet10_train.txt		table
cone	      modelnet40_shape_names.txt	tent
cup	      modelnet40_test_1024pts_fps.dat	toilet
curtain       modelnet40_test.txt		tv_stand
desk	      modelnet40_train_1024pts_fps.dat	vase
door	      modelnet40_train.txt		wardrobe
dresser       monitor				xbox
filelist.txt  night_stand
flower_pot    person


In [ ]:
test_path = '../../../shared/modelnet/modelnet40_normal_resampled/modelnet40_train_1024pts_fps.dat'


In [5]:
from src.adversarial_attacks_on_feature_dependent_graphs.dataset import PointCloudDataset
from src.adversarial_attacks_on_feature_dependent_graphs.data import *

train_dataset = PointCloudDataset(split='train')

The size of train data is 9843
Load processed data from ../../../shared/modelnet/modelnet40_normal_resampled/modelnet40_train_1024pts_fps.dat...
The size of test data is 2468
Load processed data from ../../../shared/modelnet/modelnet40_normal_resampled/modelnet40_test_1024pts_fps.dat...


100%|██████████| 7875/7875 [03:52<00:00, 33.93it/s]


In [8]:
path_to_data = '/nfs/students/bindera/data/modelnet_pyg/train_dataset.pt'
torch.save(train_dataset, path_to_data)

In [9]:
test = torch.load(path_to_data)

In [10]:
test

PointCloudDataset(7875)

In [11]:
from torch_geometric.loader import DataLoader
train_loader = DataLoader(test, batch_size=4, shuffle=True) 

In [6]:
import torch
from torch_geometric.utils import negative_sampling
edge_index = torch.as_tensor([[0,1,0], [1,2,2]])
negative_sampling(edge_index)
# tensor([[3, 0, 0, 3],
#         [2, 3, 2, 1]])

tensor([[1, 2, 2],
        [0, 0, 1]])

In [5]:
from torch.optim.lr_scheduler import ExponentialLR # (optimizer, gamma,

lr = 0.1
optimizer = torch.optim.SGD([torch.nn.Parameter(torch.tensor(1.))], lr=lr)
scheduler = ExponentialLR(optimizer=optimizer, gamma=0.5)




In [10]:
# optimizer.param_groups['lr']
# optimizer.param_groups[0]['lr']
scheduler.get_lr()

scheduler.step()
scheduler.get_lr()



[0.0125]

In [17]:
from torch.optim.lr_scheduler import ExponentialLR # (optimizer, gamma,

lr = 0.1
optimizer = torch.optim.SGD([torch.nn.Parameter(torch.tensor(1.))], lr=lr)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.1, last_epoch=-1, verbose=False)

scheduler.step()
scheduler.get_lr()
scheduler.step()
scheduler.get_lr()

[0.00010000000000000003]

In [20]:
float(1e-3)

0.001

In [1]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)
# Data(edge_index=[2, 4], x=[3, 1])

/nfs/homedirs/bindera/miniconda3/envs/test_torch/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
from torch_geometric.loader import NeighborLoader

loader = NeighborLoader(
    data,
    # Sample 30 neighbors for each node for 2 iterations
    num_neighbors=[1],# * 2,
    # Use a batch size of 128 for sampling training nodes
    batch_size=1,
    #input_nodes=data.train_mask,
)

sampled_data = next(iter(loader))

for data in loader:
    print(data.edge_index)


tensor([], size=(2, 0), dtype=torch.int64)


In [13]:
# sampled_data


In [3]:
import torch
data_folder = '/nfs/students/bindera/data/modelnet_pyg/'
test_dataset = torch.load(os.path.join(data_folder, 'test_dataset.pt'))

/nfs/homedirs/bindera/miniconda3/envs/test_torch/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [23]:
row = torch.tensor([])
for data in test_dataset:
    row.stack(data.edge_index[0])
    # print(data.edge_index)

AttributeError: 'Tensor' object has no attribute 'stack'

In [5]:
type_ = type(test_dataset)

In [22]:
from torch_geometric.utils import degree

row = torch.tensor([5, 1, 0, 2, 0])
degree(row, dtype=torch.long)



tensor([2, 1, 1, 0, 0, 1])

In [7]:
from src.adversarial_attacks_on_feature_dependent_graphs.dataset import PointCloudDataset
PointCloudDataset == type_

True

In [9]:

import seml
import pandas as pd
# from matplotlib import pyplot as plt

In [ ]:
results = seml.get_results('baselines2', to_data_frame=True)
